In [1]:
import numpy as np

In [5]:
a= np.array([1,2,3,4])

In [8]:
a1 = np.array([[1,2],[3,4]])
print(a1)

[[1 2]
 [3 4]]


In [7]:
a_ravel = a1.ravel()
print(a_ravel)


[1 2 3 4]


In [9]:
print(a1)

[[1 2]
 [3 4]]


In [11]:
b = a1.flatten()
print(b)

[1 2 3 4]


In [14]:

print(a1.__array_interface__['data'][0])
print(b.__array_interface__['data'][0])

1865685999360
1865685998976


In [16]:
a2 = np.array([[1,2,3],[4,5,6]])

In [17]:
print(a2)

[[1 2 3]
 [4 5 6]]


In [21]:
a2.resize((3,3), refcheck=False)
print(a2)


[[1 2 3]
 [4 5 6]
 [0 0 0]]


In [22]:
b2 = np.array([[1],[2],[3]])
print(b2.shape)

(3, 1)


In [24]:
b3 = np.squeeze(b2)
print(b3.shape)

(3,)


In [25]:
mat = np.array([[1,2,3],
                [3,4,5],
                [7,8,9]])

In [27]:
print(mat[0][1])

2


In [28]:
mat[:,2]

array([3, 5, 9])

In [ ]:
#[[1,2,3],
#[3,4,5],
#[7,8,9]])

In [29]:
mat[::-1,::-1]

array([[9, 8, 7],
       [5, 4, 3],
       [3, 2, 1]])

In [31]:
arr = np.array([5,4,6,7,89,10])

In [32]:
l = []
for i in arr:
    if i>15:
        l.append(i)
l=np.array(l)
print(l)


[89]


In [33]:
arr[arr>15]

array([89])