In [1]:
print("hello world")

hello world


In [2]:
import time

In [9]:
a = list(range(10000000))
b = list(range(10000000))

start_p = time.perf_counter()
c = [x + y for x,y in zip(a,b)]
end_p = time.perf_counter()
total_p=end_p-start_p
print("Python: ", total_p)



Python:  2.902028599753976


In [13]:
import numpy as np

In [10]:
a_np = list(range(10000000))
b_np = list(range(10000000))

start_n = time.perf_counter()
c_np = a_np + b_np
end_n = time.perf_counter()
total_n=end_n-start_n
print("Numpy: ", total_n)

Numpy:  0.949337899684906


In [12]:
print(f"Numpy is faaster than python by {total_p/total_n:.2f}")

Numpy is faaster than python by 3.06


In [15]:
arr_1 = np.array([1,2,3])
print(arr_1)
print(type(arr_1))

[1 2 3]
<class 'numpy.ndarray'>


In [16]:
arr_2 = np.array([[1,2,3], [4,5,6]])
print(arr_2)


[[1 2 3]
 [4 5 6]]


In [17]:
arr_4 = np.array([1,2,3], dtype=np.int8)
print(type(arr_4))

<class 'numpy.ndarray'>


In [18]:
type(arr_4[0])

numpy.int8

In [ ]:
arr_6= np.array([1,2,3, "hello"], dtype=np.int8) # every element becomes a string 

In [21]:
arr_6= np.array([1,2,3, "10"], dtype=np.float16)
print(type(arr_6[2]))

<class 'numpy.float16'>


In [23]:
arr_7 = np.arange(0,10,2)
arr_7

array([0, 2, 4, 6, 8])

In [ ]:
arr_8 = np.linspace(1, 100, 4) 
arr_8

array([  1.,  34.,  67., 100.])

In [26]:
arr_9 = np.zeros([3,5])
arr_9

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])